# User config
author: "Jimmy Ly"
tagline: "Software Engineer and Serial Hobbyist"
description: "Hi! I'm a Pharmacy student turned software engineer with an insatiable interest in solving problems. Due to my
curious nature, I'm naturally drawn to challenges that allow me to think critically and creatively. I love breathing life into ideas through software development. On my spare time, I like to jump-rope and skateboard.
"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "lyjimmy19@gmail.com"
linkedin: "https://www.linkedin.com/in/jimmy-ly-22b925134"
github: "https://github.com/lyjimmy1"


# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
